<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use common\components\ErrorHandler;

class BaseController extends Controller
{
    /**
     * @param $action
     * @return bool
     * @throws \Exception
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
//        $this->_checkLogin();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @throws \Exception
     */
    private function _checkLogin()
    {
        $user_id = intval(\Yii::$app->user->getId());
        if (empty($user_id)) {
            $this->redirect(['site/login']);
        }
    }
}